### PR TITLE
Add Documentation

### PR DESCRIPTION
**Pull request by Pranjalpok7**
Please review

### CODE REVIEW

**Review by aadarshadhakalg — CHANGES_REQUESTED** [review]
1. Rename files names, write file names in all small case. 
2. Add knowledgebaseSidebar index in each files. Ref: https://raw.githubusercontent.com/kuosc2005/website/main/knowledgebase/intro.md

3. Fix typos

**Comment by aadarshadhakalg** [comment]
Thank you @Pranjalpok7 for the PR! Great job. Kindly implement the changes I specified above.

**Comment by Pranjalpok7** [comment]
> Thank you @Pranjalpok7 for the PR! Great job. Kindly implement the changes I specified above.

@aadarshadhakalg Have made those changes, please review

**Review by kuosc2005 — CHANGES_REQUESTED** [review]
Please add 
```
---
knowledgebaseSidebar_position: 1
---
```
on top of each file.  The number after semicolon indicates the index of the file. You should keep it 

2 for contribution-guidelines
3 for code contribution
4 for docs-contribution-guidelines
5 for management contribution guidelines

Thanks.

**Pull request closed without merging**
