### PR TITLE
Projects Pages and KUCC Shoutout in Homepgae

### PR DESCRIPTION
**Pull request by aadarshadhakalg**

### CODE REVIEW

**Comment by aadarshadhakalg** [comment]
@abhiyandhakal  

Can you please help me fix the KUCC section? 
I wanted to display it like this. But sadly, I couldn't.

image

You can update the PR by pushing the changes to my fork of this repo. Thanks :)

**Comment by abhiyandhakal** [comment]
I will look into it... @aadarshadhakalg I think from now on... you can have a separate development branch to merge into... so that we can merge some incomplete stuffs too.

**Comment by abhiyandhakal** [comment]
Tbh... I think you should do that for this too... because your fork is several commits behind and some commits ahead... this is sure to create some conflicts. So, I think you'd rather merge this, and I can work on that.

**Comment by aadarshadhakalg** [comment]
Okay then, I will merge this.

**Comment by aadarshadhakalg** [comment]
Please work on this ASAP. Thank you @abhiyandhakal 🙏

**Comment by abhiyandhakal** [comment]
After I reach home

**Pull request merged**
