### PR TITLE
fix: changed the kucc shoutout location and improved it

### LINKED ISSUE #18: Fix spacing on KUCC shoutout section
Issue Description:

Uneven spacing can be seen in the current version of the website. The KUCC shoutout section is not expanded to its full container width. Also, adding a about KUOSC section above the KUCC section would look good. And the whole thing can be moved below hero section and above what we do section. And finally, about KUCC heading text can be removed and both About KUOSC and About KUCC comes under About heading. 

image

### PR DESCRIPTION
**Pull request by sanjibdahal**
This PR changes the kucc shoutout location to top and adds About section of KUOSC and KUCC with responsive design.
fixes #18 
image

### CODE REVIEW

**Comment by aadarshadhakalg** [comment]
Thanks for the PR! @sanjibdahal Good job!. Can you tweak the about section a little, so that the image and corresponding text for KUOSC and KUCC shows on alternate sides. 

Like this,

KUOSC Logo - KUOSC About Text
KUCC About Text - KUCC Logo

Also, You can keep the content for the KUCC about text same as before.

**Comment by sanjibdahal** [comment]
image

**Comment by aadarshadhakalg** [comment]
Thank you @sanjibdahal . One last change...

image

Can you please make the kucc logo come before the about kucc text in mobile view?

**Comment by sanjibdahal** [comment]
done

**Comment by aadarshadhakalg** [comment]
LGTM! Thanks for the contribution 😀

**Pull request merged**
