### PR TITLE
add: leaderboard

### PR DESCRIPTION
**Pull request by dipenkhatri7**

### CODE REVIEW

**Comment by erwinschrodinger1** [comment]
Please review new response type and design the front-end accordingly.

Thank you for you contributions in KUOSC.

**Comment by aadarshadhakalg** [comment]
Screenshot_20230901-193517
Hi @dipenkhatri7 , can you please fix the mobile too? Thanks 👍

**Comment by dipenkhatri7** [comment]
Front-end changes are completed according to new responses, including responsiveness. Please review. Thanks! 🙂

**Comment by erwinschrodinger1** [comment]
@dipenkhatri7 can you please change the ip to kuosc's ip. Currently it is pointing local host. Also please resolve the merge conflict at package-lock.json. Thank you!

**Comment by erwinschrodinger1** [comment]
@dipenkhatri7 can you please address the issue asap!

**Comment by aadarshadhakalg** [comment]
@dipenkhatri7  Can you quickly fix the responsiveness issue. So that we can merge this PR and close the issue. Thanks :)

**Comment by dipenkhatri7** [comment]
@aadarshadhakalg @erwinschrodinger1 Can you review all the changes? 🙌

**Comment by erwinschrodinger1** [comment]
Looks good for me @aadarshadhakalg can you please review it once.

**Pull request merged**
